### ISSUE TITLE
GeoIP and ISP/ASN Support Plan

### ISSUE THREAD

**Issue by acchen97** [logstash-plugins/logstash-filter-geoip#110]
### Overview
- We have had many requests to bring back ISP and ASN lookups for the GeoIP filter, which was a regression when we upgraded to using the GeoIP2 DB.
- In the GeoIP filter v2.0.7 and prior, we shipped the plugin with the legacy GeoIP Maxmind DB which came inclusive of ISP and ASN data. These plugin versions only work for Logstash 2.x and prior.
- In the GeoIP filter v4.0.0 and above, we implemented the new GeoIP2 DB which, although has the Country and City info, can no longer lookup ISP and ASN data. Maxmind now offers a separately licensed ISP Database for ISP and ASN. These plugin versions only work for Logstash 2.4 and above.

### Plans
- [x] Enable ISP and ASN lookups with the current GeoIP2 implementation. Users will have the option of plugging in the [GeoIP2 ISP Database](https://www.maxmind.com/en/geoip2-isp-database) (which must be purchased separately from Maxmind) to lookup ISP and ASN data beyond the current Country and City info that is available already. This is a high priority feature and can be expected in an upcoming release.
- [x] Support the GeoIP2 ASN Database (free)
- [x] Create a new plugin (logstash-filter-geoip_legacy) which will enable legacy GeoIP lookup on latest versions of Logstash. This is a lower priority and there may be a lag on when this is available based on user demand.

**Comment by SMAPPER** [comment]
This is awesome news. This is a core feature I use when helping organizations use Logstash for SIEM purposes. ASN information is a huge enabler for filtering out noise and identifying potentially malicious connections. Organizations that I consult with that use Elasticsearch stack commercially will likely be open to purchasing the Maxmind subscription (some already have). However, the legacy edition support would also be a huge enabler. Currently I probably help deploy 1-2 proof of concept deployments a week and today I have to do so with Logstash 2.X due to the ASN not being supported. This consists of both Elasticsearch stack deployments as well as customers using only Logstash in conjunction with their current SIEM solutions.

Also, I am writing a course called SIEM with Tactical Analytics (https://www.sans.org/event/sec555-beta/course/siem-with-tactical-analytics). In it I am using Elasticsearch, Logstash, and Kibana to show how organizations can better detect intrusions. While it is a SIEM neutral course it does help show the capabilities of the Elasticsearch stack so it would benefit everyone if ASN support was put back into Logstash 5.X. 

ASN info plays a decent part in this course. However, to let students use this feature in labs would require the free legacy databases. Right now, I have to use older copies of Elasticsearch, Logstash, and Kibana to accomplish everything.

I think having both commercial and legacy support of ASN lookups would help the security community as well as Elastic for any customers using it commercially. Thank you for moving towards providing ASN support with Logstash 5.X. I really am glad to see this moving.

**Comment by oschwald** [comment]
FWIW, a GeoLite2 ASN database is in the process of being released. See, e.g., https://github.com/maxmind/MaxMind-DB/pull/35.

**Comment by acchen97** [comment]
@SMAPPER thanks for your feedback, its helpful. Happy to see your course come to life; security analytics is indeed a very popular use case for the stack.

@oschwald hey there, this is good news, thanks for sharing! Will this be the same ASN dataset that's offered with the GeoIP2 ISP Database as well?

**Comment by oschwald** [comment]
@acchen97, the ASN data will match what is available in the GeoIP2 ISP database. The first build is now available [here](https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN), although client APIs still need to be updated with model classes for it.

**Comment by robacj** [comment]
Outstanding news! This can't come fast enough!

**Comment by suyograo** [comment]
@oschwald thanks for these links.  A free GeoLite2 ASN database is wonderful.

While I have your attention here, what would be the database type for the GeoIP2 ISN database (got from the metadata)? I couldn't find the information anywhere and I'm trying to add support to Logstash to read those database information

**Comment by suyograo** [comment]
There's a PR here to add support for ISP database https://github.com/logstash-plugins/logstash-filter-geoip/pull/111

**Comment by oschwald** [comment]
@suyograo, yes, it is `GeoIP2-ISP`.

**Comment by suyograo** [comment]
thanks @oschwald

**Comment by suyograo** [comment]
@oschwald thanks for releasing GeoIP2-ASN. Have the java clients been updated? I get an error when using this newly released ASN database with Java client `2.8.1`.

Here's the call:
```
IspResponse response = databaseReader.isp(ipAddress);
```

**Comment by oschwald** [comment]
@suyograo, the updated Java library hasn't been released. It will be released as 2.9.0. You can see [the associated changes](https://github.com/maxmind/GeoIP2-java/pull/88/files).

**Comment by pemontto** [comment]
Looks like 2.9.0 has been released

**Comment by ericmarston** [comment]
Can someone provide details on how to use this? I tried this that I found in another thread:
geoip {
      source => "clientip"
      dbtype => "isp"
      merge => true
      database => "/etc/logstash/GeoIP2-ISP.mmdb"
    }

But it gives an error of:
21:16:45.917 [LogStash::Runner] ERROR logstash.filters.geoip - Unknown setting 'dbtype' for geoip
21:16:45.919 [LogStash::Runner] ERROR logstash.filters.geoip - Unknown setting 'merge' for geoip

I then tried without those fields and it started, but then when trying to do the lookup, gave an error of:
java.lang.UnsupportedOperationException: Invalid attempt to open a GeoIP2-ISP database using the city method

Need to add this to our outputs, would love some details on how.

**Comment by robcowart** [comment]
@ericmarston, You need the latest release (4.1.1) of the GeoIP filter. The currently shipping version of Logstash still includes 4.0.4. Your error looks like you might not have yet updated. To get the latest version run.

`logstash-plugin update logstash-filter-geoip`

Rob

**Comment by ericmarston** [comment]
Unfortunately I am still getting the error. I successfully updated:
/usr/share/logstash/bin/logstash-plugin update logstash-filter-geoip
Updating logstash-filter-geoip
Updated logstash-filter-geoip 4.0.4 to 4.1.1

however, with the added config of:
geoip {
      source => "clientip"
      dbtype => "isp"
      merge => true
      database => "/etc/logstash/GeoIP2-ISP.mmdb"
    }

Logstash still won't start with the same error of:
05:20:37.163 [LogStash::Runner] ERROR logstash.filters.geoip - Unknown setting 'dbtype' for geoip
05:20:37.165 [LogStash::Runner] ERROR logstash.filters.geoip - Unknown setting 'merge' for geoip
05:20:37.174 [LogStash::Runner] ERROR logstash.agent - Cannot create pipeline {:reason=>"Something is wrong with your configuration."}

Any help is very much appreciated.

**Comment by t3chn0m4g3** [comment]
@suyograo Maxmind released support for the ASN database as well as part of the `com.maxmind.geoip2 2.9.0` and `com.maxmind.db 1.2.2` [releases](https://github.com/maxmind/GeoIP2-java/blob/master/src/main/java/com/maxmind/geoip2/DatabaseReader.java).
Do you have any chance to update this for `geoip 4.1.x`?

**Comment by robcowart** [comment]
@ericmarston remove the dbtype and merge options. I am using as simply as...

```
geoip {
    source => "[conn][dst_addr]"
    database => "/etc/logstash/geoipdbs/GeoIP2-ISP.mmdb"
}
```
The result is like this...
```
"geoip" => {
    "as_org" => "Vodafone Kabel Deutschland GmbH",
    "ip" => "123.123.123.123",
    "isp" => "Vodafone Kabel Deutschland",
    "organization" => "Vodafone Kabel Deutschland",
    "asn" => 31334
}
```

**Comment by ericmarston** [comment]
Brilliant! I guess sometimes we should pay attention to the error messages! :) I was concerned that without those parameters (which I found in another thread about this issue), it wouldn't know it was an ISP DB and wouldn't merge it with the other geoip information. 

This worked great!

**Comment by zcola** [comment]
I upgraded to 4.2.0 or not, here is my compilation script fragment
~~~
My% types = (
City => 'map',
Country => 'map',
County => 'map'
Registered_country => 'map',
Segment => ['array', 'map'],
Traits => 'map',
...
my $tree = MaxMind::DB::Writer::Tree->new(
    ip_version    => 4,
    record_size   => 32,
    database_type => 'GeoIP2-ISP',
    languages     => ['en'],
...

},
Traits => {
Isp => $ arr [17],
Organization => $ arr [19],
},
~~~
logstash return
~~~
{
"@timestamp" => 2017-06-23T08: 01: 36.884Z,
"Message_geo" => {
"City_name" => "Guangzhou",
"Time zone" => "Asia / Shanghai"
"Ip" => "1.0.8.0"
"Latitude" => 23.1167,
"Country_name" => "China"
"Country_code2" => "CN",
"Continent_code" => "AS",
"Country_code3" => "CN",
"Region_name" => "Guangdong",
"Location" => {
"Lon" => 113.25,
"Lat" => 23.1167
},
"Region_code" => "44"
"Longitude" => 113.25
},
"@version" => "1"
"Host" => "xxx"
~~~
Use python to parse the return
```
 }
    },
    "traits": {
        "organization": "\u58a8\u5c14\u672cGoldenit\u6709\u9650\u516c\u53f8",
        "isp": ""
    },
    "subdivisions": [
        {
            "iso_code": "VIC",
            "names": {
                "en": "Victoria",
                "zh_CN": ""
            }
        }
```
Is my compiler script wrong?

**Comment by zcola** [comment]
I now know that GeoIP2-ISP only ISP-related information, then I hope to support geoip2-enterprise。。。

**Comment by davisyou** [comment]
This is also my question. How do I use GeoLite2-ASN.mmdb GeoLite2-City.mmdb at the same time ?
Should I combine 2 database into 1 by myself?

**Comment by t3chn0m4g3** [comment]
That's how I am using it ...
```
# Add geo coordinates / ASN info
  if [src_ip]  {
    geoip {
      source => "src_ip"
      target => "geoip"
      database => "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-4.2.1-java/vendor/GeoLite2-City.mmdb"
    }
    geoip {
      source => "src_ip"
      target => "geoip"
      database => "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-4.2.1-java/vendor/GeoLite2-ASN.mmdb"
    }
  }
```

**Comment by suyograo** [comment]
There is no need for a new Legacy plugin since MaxMind released GeoIPLite2-ASN. v4.2.0 supports all items described above, so closing this.

**Comment by zcola** [comment]
@suyograo I use the 4.2.0, isp can not be resolved
